---
name: "Simple Checks"

on:
  workflow_call:

jobs:
  pre-commit-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --config .pre-commit-config.yaml

  lint-yaml:
    name: Lint Yaml Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: shell
          filters: |
            yaml:
              - added|modified: "**.yaml"
              - added|modified: "**.yml"

      - name: 'Yamllint'
        if: ${{ steps.filter.outputs.yaml == 'true' }}
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: '${{ steps.filter.outputs.yaml_files }}'
          strict: false
          config_file: .github/lint/yamllint.yaml
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  metadata-validation:
    name: Validate Image Metadata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: shell
          filters: |
            cue:
              - added|modified: "apps/**/metadata.yaml"
              - added|modified: ".github/lint/metadata.rules.cue"

      - name: Setup CUE
        if: ${{ steps.filter.outputs.cue == 'true' }}
        uses: cue-lang/setup-cue@a93fa358375740cd8b0078f76355512b9208acb1

      - name: Validate image metadata
        if: ${{ steps.filter.outputs.cue == 'true' }}
        shell: bash
        # Run against all files to ensure they are tested if the cue schema is changed.
        run: |
          find ./apps/ -name metadata.json | xargs -I {} cue vet --schema '#Spec' {} ./.github/lint/metadata.rules.cue

  renovate-config-validator:
    name: Validate Renovate Config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: shell
          filters: |
            renovate:
              - added|modified: ".github/renovate.json5"

      - name: Validate Renovate Config
        if: ${{ steps.filter.outputs.renovate == 'true' }}
        uses: rinchsan/renovate-config-validator@v0.2.0
        with:
          pattern: '.github/renovate.json5'
